#!/bin/sh

# Usage: run-siege 10 urls.txt

# Delivers 10 simultaneous hits to URLs randomly drawn from urls.txt

# Busts the cache. Not intended as a simulation of high load
# to a single page which would normally benefit from cache

sed "s/\$/\?cachebust=$$/" < $2 > /tmp/$$.urls
siege -c $1 -i -f /tmp/$$.urls
